config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, only: [:index, :show, :create, :new, :destroy] do
    resources :comments, only: [:create]
  end

  root 'posts#index'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy 
  validates :title, :content, presence: true
  paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to post_path(@comment.post), notice: "Comment are created Successfully"
    else
      redirect_to post_path(@comment.post), status: :unprocessable_entity
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path, notice: "Post created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to root_path, notice:"Post are deleted successfully"
    else
      redirect_to root_path, notice:"Post can't be deleted"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments_list.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-12 mx-auto">
      <% @comments.each do |comment| %>
        <div class="card mb-3 custom-card">
          <div class="card-body d-flex gap-3 ">
            <h3 class="card-title text-center mb-4"><%= image_tag "user.png", class:"img-fluid border rounded-pill border-primary", style:"max-width:80px;"%></h3>

            <div>
              <label class="fw-bold">User:</label>
              <%= comment.user_email %>
              <br>
              <label class="fw-bold mt-2">Comment:</label>
              <%= comment.content %>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for Comment.new, url: post_comments_path(@post) do |f| %>
  <div class="form-group">
    <%= f.label :content, class: "fw-bold" %>
    <%= f.text_area :content, rows: 3, cols: 10, class: "form-control" %>
    <% @comment.errors.full_messages_for(:content).each do |message| %>
      <div class="text-danger">
        <%= message %>
      </div>
    <% end %>
  </div>

  <%= f.hidden_field :post_id, value: @post.id %>

  <% if user_signed_in? %>
    <%= f.hidden_field :user_email, value: current_user.email %>
    <div class="mt-3 text-center">
      <%= f.submit "Comment", class: "btn btn-primary", id: "comment-submit" %>
    </div>
  <% else %>
    <div class="mt-3 text-center">
      <%= link_to "Submit", new_user_session_path, class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "style", "data-turbo-track":"reload" %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= render 'shared/header'%>
         <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
         <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="py-2">
  <% if user_signed_in? %>
    <%= link_to "Create New post", new_post_path, class:"btn btn-success"%>
  <% else %>
    <%= link_to "Create New post", new_user_session_path, class:"btn btn-success"%>
  <% end %>
</div>

<div class="container mt-4">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-lg-4 mb-4">
        <div class="custom-card">
          <img src="https://media.istockphoto.com/id/922745190/photo/blogging-blog-concepts-ideas-with-worktable.jpg?s=2048x2048&w=is&k=20&c=QNKuhWRD7f0P5hybe28_AHo_Wh6W93McWY157Vmmh4Q=" class="card-img-top" alt="Post Image">
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.content %></p>
            <div class="d-flex justify-content-between align-items-center">
              <p class="m-0 fw-bold"><%= image_tag "comment.png", style:"width:30px;"%> <%= post.comments.count %></p>
              <div class="btn-group">
                <%= link_to "Show Page", post_path(post), class: 'btn btn-secondary btn-sm   mx-2' %>
                <%= link_to "Delete", post_path(post), data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-lg-4">
      <%= paginate @posts %>
    </div>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function () {
    const deleteButtons = document.querySelectorAll('.btn-danger');
    deleteButtons.forEach(button => {
      button.addEventListener('click', function (event) {
        const confirmed = confirm('Are you sure you want to delete this post?');
        if (!confirmed) {
          event.preventDefault();
        }
      });
    });
  });
</script>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-4">
      <div class="card custom-card p-4">
        <h3 class="card-heading text-center mb-4">Create Post</h3>
        <%= form_for @post do |f| %>
          <div class="form-group mb-3">
            <%= f.label :title, class: "fw-bold" %>
            <%= f.text_field :title, class: "form-control" %>
            <% @post.errors.full_messages_for(:title).each do |message| %>
              <div class="text-danger">
                <%= message %>
              </div>
            <% end %>
          </div>
          <div class="form-group mb-3">
            <%= f.label :content, class: "fw-bold" %>
            <%= f.text_area :content, class: "form-control", rows: 4 %>
            <% @post.errors.full_messages_for(:content).each do |message| %>
              <div class="text-danger">
                <%= message %>
              </div>
            <% end %>
          </div>
          <% if user_signed_in? %>
             <%= f.submit "Create Post", class: "btn btn-success mt-3" %>
          <% else %>
             <%= link_to "Create Post", new_user_session_path, class: "btn btn-success mt-3" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-12 mb-4">
      <div class="card post-card">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-4">
              <img src="https://media.istockphoto.com/id/922745190/photo/blogging-blog-concepts-ideas-with-worktable.jpg?s=2048x2048&w=is&k=20&c=QNKuhWRD7f0P5hybe28_AHo_Wh6W93McWY157Vmmh4Q=" class="img-fluid" alt="Post Image" style="max-height: 200px;">
              <p class="mt-2 fw-bold"><%= image_tag "comment.png", style:"width:30px;"%> <%= @post.comments.count %></p>
            </div>
            <div class="col-lg-8">
              <div class="card-heading">
                <h2><%= @post.title %></h2>
              </div>
              <div class="card-text">
                <p><%= @post.content %></p>
              </div>
              <div>
                <%= render partial: 'comments/form', post: @post %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'comments/comments_list' %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <%= link_to "BlogApp", root_path, class:"navbar-brand text-white"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link active text-white" %>
          <% else %>
            <%= link_to "SignIn", new_user_session_path, class:"nav-link active text-white"%>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>